### ISSUE TITLE
Conda package installation failure

### ISSUE THREAD

**Issue by ibaumgart** [ckolluru/NerveTracker#1]
I'm seeing the same problem as this stackoverflow issue:

https://stackoverflow.com/questions/76040332/conda-install-cant-install-packages-from-requirements-txt

Can you please export to yaml as per the SO answer or export as pip requirements?

**Comment by ckolluru** [comment]
Pushed an environment.yml file to the repo that was made using this command

`conda env export > environment.yml`

Let me know if that works for you. Thanks.
